# Your Website Title
title: Nikolas Bourantas

# Your Website URL
url: 'https://nikolas-b.github.io/Profile/'

# Leave it default
baseurl: '' 

# Google Analytics
ga_index: UA-XXXXXXXX-X
ga_cv: UA-XXXXXXXX-X

# Index page and Profile Information
name: Nikolas Bourantas
tagline: Software Developer, IoT, Reverse Engineering
pic: profile.png # profile.png can be found at /assets/images/profile.png
description: Research Operations & Reporting Manager
description_tiny: 'Home: +60-4 | Studied: +1-408 | Work: +60-3'
email: Nikolas.bourantas@gmail.com
website: nikolas-b.github.io/Profile/ # do not add http://
linkedin: Nikolas Bourantas
github: Nikolas-B
twitter: '@enemybour'

# Files or folders to be excluded
exclude: [gitbook_source_code/]

# All the plugins for Jekyll
plugins:
  - jekyll-sitemap
  - wdm